### ISSUE TITLE
Error compiling on OS X 10.10

### ISSUE THREAD

**Issue by atomicpages** [stefanesser/suhosin#78]
Encountering an error when I compile on OS X 10.10. Here's the configure command:

```./configure –enable-suhosin –with-php-config=/Applications/XAMPP/xamppfiles/bin/php-config```

It set the compiler to `cc` (which I have) but I kept getting this error:

```
gcc -I. -I/Applications/XAMPP/suhosin-0.9.37.1 -DPHP_ATOM_INC -I/Applications/XAMPP/suhosin-0.9.37.1/include -I/Applications/XAMPP/suhosin-0.9.37.1/main -I/Applications/XAMPP/suhosin-0.9.37.1 -I/Applications/XAMPP/xamppfiles/include/php -I/Applications/XAMPP/xamppfiles/include/php/main -I/Applications/XAMPP/xamppfiles/include/php/TSRM -I/Applications/XAMPP/xamppfiles/include/php/Zend -I/Applications/XAMPP/xamppfiles/include/php/ext -I/Applications/XAMPP/xamppfiles/include/php/ext/date/lib -DHAVE_CONFIG_H -g -c /Applications/XAMPP/suhosin-0.9.37.1/ifilter.c  -fno-common -DPIC -o .libs/ifilter.o
/Applications/XAMPP/suhosin-0.9.37.1/ifilter.c:38:15: error: static declaration
      of 'strnlen' follows non-static declaration
static size_t strnlen(const char *s, size_t maxlen) {
              ^
/usr/include/string.h:133:10: note: previous declaration is here
size_t   strnlen(const char *, size_t) __OSX_AVAILABLE_STARTING(__MAC_10...
```

I switched the complier to `clang` and `clang++` to see if that did anything but no dice. I ended up commenting the function out and compiling again &ndash; it completed without errors or warnings.

Here's the rest of that function header in `/usr/include/string.h`:

```size_t   strnlen(const char *, size_t) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);```

**Note:** this might be an instance of user error. If so, let me know!

**Comment by NewEraCracker** [comment]
I wonder if your system/compiler defines HAVE_STRNLEN to 1 ... because if it doesn't, it is the cause of this problem.

I could be wrong. But I do not have any OS X install to perform any testing.

**Comment by bef** [comment]
It appears that XAMPP originally ran PHP's configure on a system without strnlen(), thus their php_config.h mistakenly contains no `#define HAVE_STRNLEN 1` on OSX 10.10.

Please refer to one of the following options:
* compile PHP yourself
* use the PHP shipped with OSX 10.0
* define HAVE_STRNLEN yourself while compiling suhosin:

        ./configure --with-php-config=/Applications/XAMPP/xamppfiles/bin/php-config
        make CFLAGS="-DHAVE_STRNLEN=1"
